<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $statement = "
        INSERT INTO `countries` (`id`, `name`, `nationality`, `iso2`, `iso3`, `code`, `currency_name`, `is_active`, `currency_symbol`, `currency_code`) VALUES
     (1, 'Afghanistan', 'Afghan', 'AF', 'AFG', '93', '', 1, '؋', 'AFN'),
     (2, 'Albania', 'Albanian', 'AL', 'ALB', '355', '', 1, 'Lek', 'ALL'),
     (3, 'Algeria', 'Algerian', 'DZ', 'DZA', '213', '', 1, 'دج', 'DZD'),
     (4, 'American Samoa', 'American Samoan', 'AS', 'ASM', '1684', '', 1, '$', 'USD'),
     (5, 'Andorra', 'Andorran', 'AD', 'AND', '376', '', 1, '€', 'EUR'),
     (6, 'Angola', 'Angolan', 'AO', 'AGO', '244', '', 1, 'Kz', 'AOA'),
     (7, 'Anguilla', 'Anguillan', 'AI', 'AIA', '1264', '', 1, '$', 'XCD'),
     (9, 'Antigua and Barbuda', 'Antiguan or Barbudan', 'AG', 'ATG', '1268', '', 1, '$', 'XCD'),
     (10, 'Argentina', 'Argentine', 'AR', 'ARG', '54', '', 1, '$', 'ARS'),
     (11, 'Armenia', 'Armenian', 'AM', 'ARM', '374', '', 1, '֏', 'AMD'),
     (12, 'Aruba', 'Aruban', 'AW', 'ABW', '297', '', 1, 'ƒ', 'AWG'),
     (13, 'Australia', 'Australian', 'AU', 'AUS', '61', '', 1, '$', 'AUD'),
     (14, 'Austria', 'Austrian', 'AT', 'AUT', '43', '', 1, '€', 'EUR'),
     (15, 'Azerbaijan', 'Azerbaijani', 'AZ', 'AZE', '994', '', 1, 'm', 'AZN'),
     (16, 'Bahamas', 'Bahamian', 'BS', 'BHS', '1242', '', 1, 'B$', 'BSD'),
     (17, 'Bahrain', 'Bahraini', 'BH', 'BHR', '973', '', 1, '.د.ب', 'BHD'),
     (18, 'Bangladesh', 'Bangladeshi', 'BD', 'BGD', '880', '', 1, '৳', 'BDT'),
     (19, 'Barbados', 'Barbadian', 'BB', 'BRB', '1246', '', 1, 'Bds$', 'BBD'),
     (20, 'Belarus', 'Belarusian', 'BY', 'BLR', '375', '', 1, 'Br', 'BYN'),
     (21, 'Belgium', 'Belgian', 'BE', 'BEL', '32', '', 1, '€', 'EUR'),
     (22, 'Belize', 'Belizean', 'BZ', 'BLZ', '501', '', 1, '$', 'BZD'),
     (23, 'Benin', 'Beninese', 'BJ', 'BEN', '229', '', 1, 'CFA', 'XOF'),
     (24, 'Bermuda', 'Bermudian', 'BM', 'BMU', '1441', '', 1, '$', 'BMD'),
     (25, 'Bhutan', 'Bhutanese', 'BT', 'BTN', '975', '', 1, 'Nu.', 'BTN'),
     (26, 'Bolivia', 'Bolivian', 'BO', 'BOL', '591', '', 1, 'Bs.', 'BOB'),
     (27, 'Bosnia and Herzegovina', 'Bosnian or Herzegovinian', 'BA', 'BIH', '387', '', 1, 'KM', 'BAM'),
     (28, 'Botswana', 'Botswanan', 'BW', 'BWA', '267', '', 1, 'P', 'BWP'),
     (30, 'Brazil', 'Brazilian', 'BR', 'BRA', '55', '', 1, 'R$', 'BRL'),
     (32, 'Brunei Darussalam', 'Bruneian', 'BN', 'BRN', '673', '', 1, 'B$', 'BND'),
     (33, 'Bulgaria', 'Bulgarian', 'BG', 'BGR', '359', '', 1, 'Лв.', 'BGN'),
     (34, 'Burkina Faso', 'Burkinabé', 'BF', 'BFA', '226', '', 1, 'CFA', 'XOF'),
     (35, 'Burundi', 'Burundian', 'BI', 'BDI', '257', '', 1, 'FBu', 'BIF'),
     (36, 'Cambodia', 'Cambodian', 'KH', 'KHM', '855', '', 1, 'KHR', 'KHR'),
     (37, 'Cameroon', 'Cameroonian', 'CM', 'CMR', '237', '', 1, 'FCFA', 'XAF'),
     (38, 'Canada', 'Canadian', 'CA', 'CAN', '1', '', 1, '$', 'CAD'),
     (39, 'Cape Verde', 'Cape Verde', 'CV', 'CPV', '238', '', 1, '$', 'CVE'),
     (40, 'Cayman Islands', 'Caymanian', 'KY', 'CYM', '1345', '', 1, '$', 'KYD'),
     (41, 'Central African Republic', 'Central African', 'CF', 'CAF', '236', '', 1, 'FCFA', 'XAF'),
     (42, 'Chad', 'Chadian', 'TD', 'TCD', '235', '', 1, 'FCFA', 'XAF'),
     (43, 'Chile', 'Chilean', 'CL', 'CHL', '56', '', 1, '$', 'CLP'),
     (44, 'China', 'Chinese', 'CN', 'CHN', '86', '', 1, '¥', 'CNY'),
     (45, 'Christmas Island', 'Christmas Island', 'CX', NULL, '61', '', 1, '$', 'AUD'),
     (46, 'Cocos (Keeling) Islands', 'Cocos Island', 'CC', NULL, '672', '', 1, '$', 'AUD'),
     (47, 'Colombia', 'Colombian', 'CO', 'COL', '57', '', 1, '$', 'COP'),
     (48, 'Comoros', 'Comorian', 'KM', 'COM', '269', '', 1, 'CF', 'KMF'),
     (49, 'Congo', 'Congolese', 'CG', 'COG', '242', '', 1, 'FC', 'XAF'),
     (50, 'Congo, the Democratic Republic of the', 'Congolese', 'CD', 'COD', '242', '', 1, 'FC', 'CDF'),
     (51, 'Cook Islands', 'Cook Island', 'CK', 'COK', '682', '', 1, '$', 'NZD'),
     (52, 'Costa Rica', 'Costa Rican', 'CR', 'CRI', '506', '', 1, '₡', 'CRC'),
     (53, 'Cote D\'Ivoire', 'Ivorian', 'CI', 'CIV', '225', '', 1, 'CFA', 'XOF'),
     (54, 'Croatia', 'Croatian', 'HR', 'HRV', '385', '', 1, 'kn', 'HRK'),
     (55, 'Cuba', 'Cuban', 'CU', 'CUB', '53', '', 1, '$', 'CUP'),
     (56, 'Cyprus', 'Cypriot', 'CY', 'CYP', '357', '', 1, '€', 'EUR'),
     (57, 'Czech Republic', 'Czech', 'CZ', 'CZE', '420', '', 1, 'Kč', 'CZK'),
     (58, 'Denmark', 'Danish', 'DK', 'DNK', '45', '', 1, 'Kr.', 'DKK'),
     (59, 'Djibouti', 'Djiboutian', 'DJ', 'DJI', '253', '', 1, 'Fdj', 'DJF'),
     (60, 'Dominica', 'Dominican', 'DM', 'DMA', '1767', '', 1, '$', 'XCD'),
     (61, 'Dominican Republic', 'Dominican', 'DO', 'DOM', '1809', '', 1, '$', 'DOP'),
     (62, 'Ecuador', 'Ecuadorian', 'EC', 'ECU', '593', '', 1, '$', 'USD'),
     (63, 'Egypt', 'Egyptian', 'EG', 'EGY', '20', '', 1, 'ج.م', 'EGP'),
     (64, 'El Salvador', 'Salvadoran', 'SV', 'SLV', '503', '', 1, '$', 'USD'),
     (65, 'Equatorial Guinea', 'Equatoguinean', 'GQ', 'GNQ', '240', '', 1, 'FCFA', 'XAF'),
     (66, 'Eritrea', 'Eritrean', 'ER', 'ERI', '291', '', 1, 'Nfk', 'ERN'),
     (67, 'Estonia', 'Estonian', 'EE', 'EST', '372', '', 1, '€', 'EUR'),
     (68, 'Ethiopia', 'Ethiopian', 'ET', 'ETH', '251', '', 1, 'Nkf', 'ETB'),
     (69, 'Falkland Islands (Malvinas)', 'Falkland Island', 'FK', 'FLK', '500', '', 1, '£', 'FKP'),
     (70, 'Faroe Islands', 'Faroese', 'FO', 'FRO', '298', '', 1, 'Kr.', 'DKK'),
     (71, 'Fiji', 'Fijian', 'FJ', 'FJI', '679', '', 1, 'FJ$', 'FJD'),
     (72, 'Finland', 'Finnish', 'FI', 'FIN', '358', '', 1, '€', 'EUR'),
     (73, 'France', 'French', 'FR', 'FRA', '33', '', 1, '€', 'EUR'),
     (74, 'French Guiana', 'French Guianese', 'GF', 'GUF', '594', '', 1, '€', 'EUR'),
     (75, 'French Polynesia', 'French Polynesian', 'PF', 'PYF', '689', '', 1, '₣', 'XPF'),
     (77, 'Gabon', 'Gabonese', 'GA', 'GAB', '241', '', 1, 'FCFA', 'XAF'),
     (78, 'Gambia', 'Gambian', 'GM', 'GMB', '220', '', 1, 'D', 'GMD'),
     (79, 'Georgia', 'Georgian', 'GE', 'GEO', '995', '', 1, 'ლ', 'GEL'),
     (80, 'Germany', 'German', 'DE', 'DEU', '49', '', 1, '€', 'EUR'),
     (81, 'Ghana', 'Ghanaian', 'GH', 'GHA', '233', '', 1, 'GH₵', 'GHS'),
     (82, 'Gibraltar', 'Gibraltar', 'GI', 'GIB', '350', '', 1, '£', 'GIP'),
     (83, 'Greece', 'Hellenic', 'GR', 'GRC', '30', '', 1, '€', 'EUR'),
     (84, 'Greenland', 'Greenlandic', 'GL', 'GRL', '299', '', 1, 'Kr.', 'DKK'),
     (85, 'Grenada', 'Grenadian', 'GD', 'GRD', '1473', '', 1, '$', 'XCD'),
     (86, 'Guadeloupe', 'Guadeloupe', 'GP', 'GLP', '590', '', 1, '€', 'EUR'),
     (87, 'Guam', 'Guamanian', 'GU', 'GUM', '1671', '', 1, '$', 'USD'),
     (88, 'Guatemala', 'Guatemalan', 'GT', 'GTM', '502', '', 1, 'Q', 'GTQ'),
     (89, 'Guinea', 'Guinean', 'GN', 'GIN', '224', '', 1, 'FG', 'GNF'),
     (90, 'Guinea-Bissau', 'Bissau-Guinean', 'GW', 'GNB', '245', '', 1, 'CFA', 'XOF'),
     (91, 'Guyana', 'Guyanese', 'GY', 'GUY', '592', '', 1, '$', 'GYD'),
     (92, 'Haiti', 'Haitian', 'HT', 'HTI', '509', '', 1, 'G', 'HTG'),
     (95, 'Honduras', 'Honduran', 'HN', 'HND', '504', '', 1, 'L', 'HNL'),
     (96, 'Hong Kong', 'Hong Kongese', 'HK', 'HKG', '852', '', 1, '$', 'HKD'),
     (97, 'Hungary', 'Hungarian', 'HU', 'HUN', '36', '', 1, 'Ft', 'HUF'),
     (98, 'Iceland', 'Icelandic', 'IS', 'ISL', '354', '', 1, 'kr', 'ISK'),
     (99, 'India', 'Indian', 'IN', 'IND', '91', '', 1, '₹', 'INR'),
     (100, 'Indonesia', 'Indonesian', 'ID', 'IDN', '62', '', 1, 'Rp', 'IDR'),
     (101, 'Iran, Islamic Republic of', 'Iranian', 'IR', 'IRN', '98', '', 1, '﷼', 'IRR'),
     (102, 'Iraq', 'Iraqi', 'IQ', 'IRQ', '964', '', 1, 'د.ع', 'IQD'),
     (103, 'Ireland', 'Irish', 'IE', 'IRL', '353', '', 1, '€', 'EUR'),
     (104, 'Israel', 'Israeli', 'IL', 'ISR', '972', '', 1, '₪', 'ILS'),
     (105, 'Italy', 'Italian', 'IT', 'ITA', '39', '', 1, '€', 'EUR'),
     (106, 'Jamaica', 'Jamaican', 'JM', 'JAM', '1876', '', 1, 'J$', 'JMD'),
     (107, 'Japan', 'Japanese', 'JP', 'JPN', '81', '', 1, '¥', 'JPY'),
     (108, 'Jordan', 'Jordanian', 'JO', 'JOR', '962', '', 1, 'ا.د', 'JOD'),
     (109, 'Kazakhstan', 'Kazakhstani', 'KZ', 'KAZ', '7', '', 1, 'лв', 'KZT'),
     (110, 'Kenya', 'Kenyan', 'KE', 'KEN', '254', '', 1, 'KSh', 'KES'),
     (111, 'Kiribati', 'I-Kiribati', 'KI', 'KIR', '686', '', 1, '$', 'AUD'),
     (112, 'Korea, Democratic People\'s Republic of', 'North Korean', 'KP', 'PRK', '850', '', 1, '₩', 'KPW'),
     (113, 'Korea, Republic of', 'South Korean', 'KR', 'KOR', '82', '', 1, '₩', 'KRW'),
     (114, 'Kuwait', 'Kuwaiti', 'KW', 'KWT', '965', '', 1, 'ك.د', 'KWD'),
     (115, 'Kyrgyzstan', 'Kyrgyzstani', 'KG', 'KGZ', '996', '', 1, 'лв', 'KGS'),
     (116, 'Lao People\'s Democratic Republic', 'Laotian', 'LA', 'LAO', '856', '', 1, '₭', 'LAK'),
     (117, 'Latvia', 'Latvian', 'LV', 'LVA', '371', '', 1, '€', 'EUR'),
     (118, 'Lebanon', 'Lebanese', 'LB', 'LBN', '961', '', 1, '£', 'LBP'),
     (119, 'Lesotho', 'Basotho', 'LS', 'LSO', '266', '', 1, 'L', 'LSL'),
     (120, 'Liberia', 'Liberian', 'LR', 'LBR', '231', '', 1, '$', 'LRD'),
     (121, 'Libyan Arab Jamahiriya', 'Libyan', 'LY', 'LBY', '218', '', 1, 'د.ل', 'LYD'),
     (122, 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE', '423', '', 1, 'CHf', 'CHF'),
     (123, 'Lithuania', 'Lithuanian', 'LT', 'LTU', '370', '', 1, '€', 'EUR'),
     (124, 'Luxembourg', 'Luxembourgish', 'LU', 'LUX', '352', '', 1, '€', 'EUR'),
     (125, 'Macao', 'Macanese', 'MO', 'MAC', '853', '', 1, '$', 'MOP'),
     (126, 'Macedonia, the Former Yugoslav Republic of', 'Macedonian', 'MK', 'MKD', '389', '', 1, 'ден', 'MKD'),
     (127, 'Madagascar', 'Malagasy', 'MG', 'MDG', '261', '', 1, 'Ar', 'MGA'),
     (128, 'Malawi', 'Malawian', 'MW', 'MWI', '265', '', 1, 'MK', 'MWK'),
     (129, 'Malaysia', 'Malaysian', 'MY', 'MYS', '60', '', 1, 'RM', 'MYR'),
     (130, 'Maldives', 'Maldivian', 'MV', 'MDV', '960', '', 1, 'Rf', 'MVR'),
     (131, 'Mali', 'Malian', 'ML', 'MLI', '223', '', 1, 'CFA', 'XOF'),
     (132, 'Malta', 'Maltese', 'MT', 'MLT', '356', '', 1, '€', 'EUR'),
     (133, 'Marshall Islands', 'MARSHALL ISLANDS', 'MH', 'MHL', '692', '', 1, '$', 'USD'),
     (134, 'Martinique', 'Martinican', 'MQ', 'MTQ', '596', '', 1, '€', 'EUR'),
     (135, 'Mauritania', 'Mauritanian', 'MR', 'MRT', '222', '', 1, 'MRU', 'MRO'),
     (136, 'Mauritius', 'Mauritian', 'MU', 'MUS', '230', '', 1, '₨', 'MUR'),
     (137, 'Mayotte', 'Mahoran', 'YT', NULL, '269', '', 1, '€', 'EUR'),
     (138, 'Mexico', 'Mexican', 'MX', 'MEX', '52', '', 1, '$', 'MXN'),
     (139, 'Micronesia, Federated States of', 'Micronesian', 'FM', 'FSM', '691', '', 1, '$', 'USD'),
     (140, 'Moldova, Republic of', 'Moldovan', 'MD', 'MDA', '373', '', 1, 'L', 'MDL'),
     (141, 'Monaco', 'Monacan', 'MC', 'MCO', '377', '', 1, '€', 'EUR'),
     (142, 'Mongolia', 'Mongolian', 'MN', 'MNG', '976', '', 1, '₮', 'MNT'),
     (143, 'Montserrat', 'Montserratian', 'MS', 'MSR', '1664', '', 1, '$', 'XCD'),
     (144, 'Morocco', 'Moroccan', 'MA', 'MAR', '212', '', 1, 'DH', 'MAD'),
     (145, 'Mozambique', 'Mozambican', 'MZ', 'MOZ', '258', '', 1, 'MT', 'MZN'),
     (146, 'Myanmar', 'Burmese', 'MM', 'MMR', '95', '', 1, 'K', 'MMK'),
     (147, 'Namibia', 'Namibian', 'NA', 'NAM', '264', '', 1, '$', 'NAD'),
     (148, 'Nauru', 'Nauruan', 'NR', 'NRU', '674', '', 1, '$', 'AUD'),
     (149, 'Nepal', 'Nepali', 'NP', 'NPL', '977', '', 1, '₨', 'NPR'),
     (150, 'Netherlands', 'Dutch', 'NL', 'NLD', '31', '', 1, '€', 'EUR'),
     (152, 'New Caledonia', 'New Caledonian', 'NC', 'NCL', '687', '', 1, '₣', 'XPF'),
     (153, 'New Zealand', 'New Zealand', 'NZ', 'NZL', '64', '', 1, '$', 'NZD'),
     (154, 'Nicaragua', 'Nicaraguan', 'NI', 'NIC', '505', '', 1, 'C$', 'NIO'),
     (155, 'Niger', 'Nigerian', 'NE', 'NER', '227', '', 1, 'CFA', 'XOF'),
     (156, 'Nigeria', 'Nigerian', 'NG', 'NGA', '234', '', 1, '₦', 'NGN'),
     (157, 'Niue', 'Niuean', 'NU', 'NIU', '683', '', 1, '$', 'NZD'),
     (158, 'Norfolk Island', 'Norfolk Island', 'NF', 'NFK', '672', '', 1, '$', 'AUD'),
     (159, 'Northern Mariana Islands', 'Northern Marianan', 'MP', 'MNP', '1670', '', 1, '$', 'USD'),
     (160, 'Norway', 'Norwegian', 'NO', 'NOR', '47', '', 1, 'kr', 'NOK'),
     (161, 'Oman', 'Omani', 'OM', 'OMN', '968', '', 1, '.ع.ر', 'OMR'),
     (162, 'Pakistan', 'Pakistani', 'PK', 'PAK', '92', '', 1, '₨', 'PKR'),
     (163, 'Palau', 'Palauan', 'PW', 'PLW', '680', '', 1, '$', 'USD'),
     (164, 'Palestinian Territory, Occupied', 'Palestinian', 'PS', NULL, '970', '', 1, '₪', 'ILS'),
     (165, 'Panama', 'Panamanian', 'PA', 'PAN', '507', '', 1, 'B/.', 'PAB'),
     (166, 'Papua New Guinea', 'Papuan', 'PG', 'PNG', '675', '', 1, 'K', 'PGK'),
     (167, 'Paraguay', 'Paraguayan', 'PY', 'PRY', '595', '', 1, '₲', 'PYG'),
     (168, 'Peru', 'Peruvian', 'PE', 'PER', '51', '', 1, 'S/.', 'PEN'),
     (169, 'Philippines', 'Filipino', 'PH', 'PHL', '63', '', 1, '₱', 'PHP'),
     (171, 'Poland', 'Polish', 'PL', 'POL', '48', '', 1, 'zł', 'PLN'),
     (172, 'Portugal', 'Portuguese', 'PT', 'PRT', '351', '', 1, '€', 'EUR'),
     (173, 'Puerto Rico', 'Puerto Rican', 'PR', 'PRI', '1787', '', 1, '$', 'USD'),
     (174, 'Qatar', 'Qatari', 'QA', 'QAT', '974', '', 1, 'ق.ر', 'QAR'),
     (175, 'Reunion', 'Reunionese', 'RE', 'REU', '262', '', 1, '€', 'EUR'),
     (176, 'Romania', 'Romanian', 'RO', 'ROM', '40', '', 1, 'lei', 'RON'),
     (177, 'Russian Federation', 'Russian', 'RU', 'RUS', '70', '', 1, '₽', 'RUB'),
     (178, 'Rwanda', 'Rwandan', 'RW', 'RWA', '250', '', 1, 'FRw', 'RWF'),
     (179, 'Saint Helena', 'Saint Helenian', 'SH', 'SHN', '290', '', 1, '£', 'SHP'),
     (180, 'Saint Kitts and Nevis', 'Kittitian', 'KN', 'KNA', '1869', '', 1, '$', 'XCD'),
     (181, 'Saint Lucia', 'Saint Lucian', 'LC', 'LCA', '1758', '', 1, '$', 'XCD'),
     (182, 'Saint Pierre and Miquelon', 'Saint-Pierrais', 'PM', 'SPM', '508', '', 1, '€', 'EUR'),
     (183, 'Saint Vincent and the Grenadines', 'Saint Vincentian', 'VC', 'VCT', '1784', '', 1, '$', 'XCD'),
     (184, 'Samoa', 'Samoan', 'WS', 'WSM', '684', '', 1, 'SAT', 'WST'),
     (185, 'San Marino', 'Sammarinese', 'SM', 'SMR', '378', '', 1, '€', 'EUR'),
     (186, 'Sao Tome and Principe', 'Sao Tomean', 'ST', 'STP', '239', '', 1, 'Db', 'STD'),
     (187, 'Saudi Arabia', 'Saudi Arabian', 'SA', 'SAU', '966', '', 1, '﷼', 'SAR'),
     (188, 'Senegal', 'Senegalese', 'SN', 'SEN', '221', '', 1, 'CFA', 'XOF'),
     (189, 'Serbia', 'Serbian', 'CS', NULL, '381', '', 1, 'din', 'RSD'),
     (190, 'Seychelles', 'Seychellois', 'SC', 'SYC', '248', '', 1, 'SRe', 'SCR'),
     (191, 'Sierra Leone', 'Sierra Leonean', 'SL', 'SLE', '232', '', 1, 'Le', 'SLL'),
     (192, 'Singapore', 'Singaporean', 'SG', 'SGP', '65', '', 1, '$', 'SGD'),
     (193, 'Slovakia', 'Slovak', 'SK', 'SVK', '421', '', 1, '€', 'EUR'),
     (194, 'Slovenia', 'Slovenian', 'SI', 'SVN', '386', '', 1, '€', 'EUR'),
     (195, 'Solomon Islands', 'Solomon Island', 'SB', 'SLB', '677', '', 1, 'Si$', 'SBD'),
     (196, 'Somalia', 'Somalian', 'SO', 'SOM', '252', '', 1, 'Sh.so.', 'SOS'),
     (197, 'South Africa', 'South African', 'ZA', 'ZAF', '27', '', 1, 'R', 'ZAR'),
     (199, 'Spain', 'Spanish', 'ES', 'ESP', '34', '', 1, '€', 'EUR'),
     (200, 'Sri Lanka', 'Sri Lankan', 'LK', 'LKA', '94', '', 1, 'Rs', 'LKR'),
     (201, 'Sudan', 'Sudanese', 'SD', 'SDN', '249', '', 1, '.س.ج', 'SDG'),
     (202, 'Suriname', 'Surinamese', 'SR', 'SUR', '597', '', 1, '$', 'SRD'),
     (203, 'Svalbard and Jan Mayen', 'Svalbard', 'SJ', 'SJM', '47', '', 1, 'kr', 'NOK'),
     (204, 'Swaziland', 'Swazi', 'SZ', 'SWZ', '268', '', 1, 'E', 'SZL'),
     (205, 'Sweden', 'Swedish', 'SE', 'SWE', '46', '', 1, 'kr', 'SEK'),
     (206, 'Switzerland', 'Swiss', 'CH', 'CHE', '41', '', 1, 'CHf', 'CHF'),
     (207, 'Syrian Arab Republic', 'Syrian', 'SY', 'SYR', '963', '', 1, 'LS', 'SYP'),
     (208, 'Taiwan, Province of China', 'Taiwanese', 'TW', 'TWN', '886', '', 1, '$', 'TWD'),
     (209, 'Tajikistan', 'Tajikistani', 'TJ', 'TJK', '992', '', 1, 'SM', 'TJS'),
     (210, 'Tanzania, United Republic of', 'Tanzanian', 'TZ', 'TZA', '255', '', 1, 'TSh', 'TZS'),
     (211, 'Thailand', 'Thai', 'TH', 'THA', '66', '', 1, '฿', 'THB'),
     (212, 'Timor-Leste', 'Timorese', 'TL', NULL, '670', '', 1, '$', 'USD'),
     (213, 'Togo', 'Togolese', 'TG', 'TGO', '228', '', 1, 'CFA', 'XOF'),
     (214, 'Tokelau', 'Tokelauan', 'TK', 'TKL', '690', '', 1, '$', 'NZD'),
     (215, 'Tonga', 'Tongan', 'TO', 'TON', '676', '', 1, '$', 'TOP'),
     (216, 'Trinidad and Tobago', 'Trinidadian', 'TT', 'TTO', '1868', '', 1, '$', 'TTD'),
     (217, 'Tunisia', 'Tunisian', 'TN', 'TUN', '216', '', 1, 'ت.د', 'TND'),
     (218, 'Turkey', 'Turkish', 'TR', 'TUR', '90', '', 1, '₺', 'TRY'),
     (219, 'Turkmenistan', 'Turkmen', 'TM', 'TKM', '993', '', 1, 'T', 'TMT'),
     (220, 'Turks and Caicos Islands', 'Turks and Caicos Island', 'TC', 'TCA', '1649', '', 1, '$', 'USD'),
     (221, 'Tuvalu', 'Tuvaluan', 'TV', 'TUV', '688', '', 1, '$', 'AUD'),
     (222, 'Uganda', 'Ugandan', 'UG', 'UGA', '256', '', 1, 'USh', 'UGX'),
     (223, 'Ukraine', 'Ukrainian', 'UA', 'UKR', '380', '', 1, '₴', 'UAH'),
     (224, 'United Arab Emirates', 'Emirati', 'AE', 'ARE', '971', '', 1, 'AED', 'AED'),
     (225, 'United Kingdom', 'British', 'GB', 'GBR', '44', '', 1, '£', 'GBP'),
     (226, 'United States', 'American', 'US', 'USA', '1', '', 1, '$', 'USD'),
     (228, 'Uruguay', 'Uruguayan', 'UY', 'URY', '598', '', 1, '$', 'UYU'),
     (229, 'Uzbekistan', 'Uzbekistani', 'UZ', 'UZB', '998', '', 1, 'лв', 'UZS'),
     (230, 'Vanuatu', 'Vanuatuan', 'VU', 'VUT', '678', '', 1, 'VT', 'VUV'),
     (231, 'Venezuela', 'Venezuelan', 'VE', 'VEN', '58', '', 1, 'Bs', 'VEF'),
     (232, 'Viet Nam', 'Vietnamese', 'VN', 'VNM', '84', '', 1, '₫', 'VND'),
     (235, 'Wallis and Futuna', 'Wallis and Futuna', 'WF', 'WLF', '681', '', 1, '₣', 'XPF'),
     (236, 'Western Sahara', 'Sahrawi', 'EH', 'ESH', '212', '', 1, 'MAD', 'MAD'),
     (237, 'Yemen', 'Yemeni', 'YE', 'YEM', '967', '', 1, '﷼', 'YER'),
     (238, 'Zambia', 'Zambian', 'ZM', 'ZMB', '260', '', 1, 'ZK', 'ZMW'),
     (239, 'Zimbabwe', 'Zimbabwean', 'ZW', 'ZWE', '263', '', 1, '$', 'ZWL');
        ";
     DB::unprepared($statement);
    }
}
